#define WINDOW_WIDTH 1200
#define WINDOW_HEIGHT 900

#define NAME_INPUT_WIDTH 100
#define DATE_INPUT_WIDTH 30

#define SCROLL_REGION_WIDTH 1000
#define SCROLL_REGION_HEIGHT 600

#define NEW_PERSON_BTTN_WIDTH 200
#define NEW_PERSON_BTTN_HEIGHT 60

#define PERSON_BOX_WIDTH 70
#define PERSON_BOX_HEIGHT 50